### ISSUE TITLE
Todas las funciones deben estar en el archivo Main.c

### ISSUE THREAD

**Issue by JoelBarcenasMartinez** [HeberSegura/LaboratorioCViernes#1]
Buen día.
Se notó que con cada commit, tu subías la codificacion de los problemas, y eliminabas los anteriores. 
Esto no debe ser así, el codigo de los problemas debe ser uno abajo del anterior ejemplo:
Codigo de Problema 1,
Codigo de Problema 2,
Codigo de Problema 3
Codigo de Problema 4

consecutivo, con sus respectivos scansf y printf,

**Comment by HeberSegura** [comment]
Ya se hicieron las correcciones, gracias por la aclaración.
